name: VMOD Issue
description: Vehicle modeling, simulation, or analysis task
title: "VMOD-ISSUE: <short, descriptive title>"
labels: ["VMOD"]
body:

  - type: markdown
    attributes:
      value: |
        ## Vehicle Modeling & Simulation Issue
        Use this template for modeling tasks, simulations, analyses, validation, or tooling related to VMOD.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Objective
      description: What is being modeled, analyzed, or fixed? What question are we trying to answer?
      placeholder: |
        Example:
        Develop a nonlinear load transfer model for lateral acceleration sweeps
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope & Deliverables
      description: What is in-scope and out-of-scope? What constitutes “done”?
      placeholder: |
        - In scope: steady-state model, parameterized by Fz and track width
        - Out of scope: transient roll dynamics
        - Deliverable: validated Python module + plot
    validations:
      required: true

  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions
      description: Key modeling assumptions or simplifications
      placeholder: |
        - Quasi-steady-state
        - Rigid chassis
        - Linear suspension stiffness

  - type: textarea
    id: approach
    attributes:
      label: Proposed Approach
      description: How do you plan to solve this? Equations, tools, references, etc.
      placeholder: |
        - Use energy-based formulation
        - Implement in Python
        - Validate against reference dataset

  - type: textarea
    id: validation
    attributes:
      label: Validation / Acceptance Criteria
      description: How will correctness be evaluated?
      placeholder: |
        - Compare against known steady-state solution
        - Check limiting cases
        - Unit tests pass

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Blockers
      description: Link any blocking or prerequisite issues
      placeholder: |
        Blocked by:
        - #123
        - #124

  - type: textarea
    id: references
    attributes:
      label: References
      description: Papers, notes, textbooks, prior work, or links
      placeholder: |
        - Milliken & Milliken
        - Pacejka MF 5.2
        - Internal note: docs/load_transfer.md

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Anything else that might be useful later
